---
image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      mkdir build
      cmake -S . -B build/
      cmake --build build/
      ctest --test-dir build/

github:
  prebuilds:
    addComment: true

vscode:
  extensions:
    - xaver.clang-format
...
