---
name: check_shell_scripts

'on':
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  run_shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Install shellcheck
        run: |
          sudo apt-get install shellcheck

      - name: display shellcheck version
        run: |
          shellcheck --version

      - name: run check_shell_scripts
        run: |
          ./check_shell_scripts.sh
...
