---
name: check_shell_scripts

'on':
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  run_shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install shellcheck
        run: |
          sudo apt-get install shellcheck

      - name: display shellcheck version
        run: |
          shellcheck --version

      - name: run check_shell_scripts
        run: |
          ./check_shell_scripts.sh
...
