---
name: generate_reports

'on':
  workflow_dispatch:
  schedule:
    - cron: '7 9 1 * *'

permissions:
  contents: read

env:
  scripts_path: ${{github.workspace}}/scripts
  gxx: g++
  clangxx: clang++

jobs:
  generate_reports:
    name: Generate reports
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install boost
        run: |
          sudo apt-get update
          sudo apt-get install libboost-all-dev

      - name: Install lcov
        run: |
          sudo apt-get install lcov

      - name: Install llvm
        run: |
          sudo apt-get install llvm

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Create virtual environment
        run: |
          python3 -m venv ./venv
          source ./venv/bin/activate
          echo "PATH=${PATH}" >> "${GITHUB_ENV}"

      - name: Install gcovr
        run: |
          python -m pip install --upgrade pip
          sudo pip install gcovr

      - name: Show versions
        run: |
          ${{env.gxx}} --version
          gcov --version
          lcov --version
          ${{env.clangxx}} --version
          llvm-cov --version

      - name: Generate coverage reports
        working-directory: ${{env.scripts_path}}
        run: |
          ./generate_raw_coverage_data_gxx.sh
          ./run_gcovr_html.sh
          ./run_gcovr_sonarqube.sh
          ./run_gcovr_cobertura.sh
          ./run_lcov_and_genhtml.sh
          ./generate_raw_coverage_data_clangxx.sh
          ./run_llvm-cov.sh

      - name: Upload generated reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage_reports
          path: coverage_reports
          if-no-files-found: error
          retention-days: 5
